#!/bin/bash

# Colors
BLACK="\033[1;40;30m"
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
MAGENTA="\033[1;35m"
CYAN="\033[1;36m"
WHITE="\033[1;37m"
RESET="\033[0m"

# Get OS
os="$(source /etc/os-release && echo "${PRETTY_NAME}") $(uname -m)"

# Get Kernel
kr="$(uname -r)"

# Count packages
pk="$(pacman -Q | wc -l)"

# Get shell
sh="$(basename "$SHELL")"

# Get Terminal Emulator
# https://www.reddit.com/r/okbuddylinux/comments/n7mj69/when_the_linux_is_sus/
tm="$(ps -p $(ps -o ppid= -p $PPID) -o comm=)"

# Get window manager
# https://github.com/dylanaraps/neofetch/blob/master/neofetch
get_wm() {
    id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
    id=${id##* }
    wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t)
    wm=${wm/*WM_NAME = }
    wm=${wm/\"}
    wm=${wm/\"*}
    echo -e "$wm"
}

# Get song
get_song() {
    song="$(playerctl metadata --format '{{ artist }} | {{ title }}' 2>/dev/null)"
    if [[ -z $song ]]; then
        echo " "
    else
        echo -e "${MAGENTA}  mu  ${WHITE}$song"
    fi
}

# Print the info to the screen
echo
echo -e "${CYAN}      /\       ${MAGENTA}  os  ${WHITE}${os}"
echo -e "${CYAN}     /  \      ${YELLOW}  kr  ${WHITE}${kr}"
echo -e "${CYAN}    /\   \     ${BLUE}  pk  ${WHITE}${pk}"
echo -e "   /      \    ${RED}  sh  ${WHITE}${sh}"
echo -e "  /   ,,   \   ${CYAN}😸 tm  ${WHITE}${tm}"
echo -e " /   |  |  -\  ${GREEN}  wm  ${WHITE}$(get_wm)"
echo -e "/_-''    ''-_\ $(get_song)"
echo
echo -e "               ${YELLOW}󰮯  · · · ${MAGENTA}  ${CYAN}  ${RED}  ${BLUE}  ${GREEN} ${RESET}"
