#!/bin/bash

# Colors
BLACK="\033[1;40;30m"
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
MAGENTA="\033[1;35m"
CYAN="\033[1;36m"
WHITE="\033[1;37m"
RESET="\033[0m"

# Get OS
os="$(source /etc/os-release && echo "${PRETTY_NAME}") $(uname -m)"

# Get Kernel
kr="$(uname -r)"

# Count packages
pk="$(pacman -Q | wc -l)"

# Get shell
sh="$(basename "$SHELL")"

# Get Terminal Emulator
# https://unix.stackexchange.com/questions/264329/get-the-terminal-emulator-name-inside-the-shell-script
tm=$(ps -o comm= -p "$(($(ps -o ppid= -p "$(($(ps -o sid= -p "$$")))")))")

# Get window manager
# https://github.com/dylanaraps/neofetch/blob/master/neofetch
get_wm() {
    id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
    id=${id##* }
    wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t)
    wm=${wm/*WM_NAME = }
    wm=${wm/\"}
    wm=${wm/\"*}
    echo -e "$wm"
}

# Get the init
# https://github.com/Mangeshrex/rxfetch
get_init() {
    if [ -f '/sbin/openrc' ]; then
        echo 'openrc'
    else
        cut -d ' ' -f 1 /proc/1/comm
    fi
}

# Print the info to the screen
echo
echo -e "${CYAN}      /\       ${MAGENTA}  os  ${WHITE}${os}"
echo -e "${CYAN}     /  \      ${YELLOW}  kr  ${WHITE}${kr}"
echo -e "${CYAN}    /\`'.,\     ${BLUE}  pk  ${WHITE}${pk}"
echo -e "${CYAN}   /     ',    ${RED}  sh  ${WHITE}${sh}"
echo -e "${CYAN}  /      ,\`\   ${CYAN}😸 tm  ${WHITE}${tm}"
echo -e "${CYAN} /   ,.'\`.  \  ${GREEN}  wm  ${WHITE}$(get_wm)"
echo -e "${CYAN}/.,'\`     \`'.\ ${MAGENTA}  in  ${WHITE}$(get_init)"
echo
echo -e "               ${YELLOW}󰮯  · · · ${MAGENTA}  ${CYAN}  ${RED}  ${BLUE}  ${GREEN} ${RESET}"
